actionInterval: 1000
supportedChains:
  - chainId: 1
    chainName: Solana
    nodeUrl: https://api.devnet.solana.com
    nativeCurrencySymbol: SOL
    tokenBridgeAddress: DZnkkTmCiFWfYTfT41X3Rd1kDgozqzxWaHqsw6W4x2oe
    bridgeAddress: 3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5
    wrappedAsset: So11111111111111111111111111111111111111112
  - chainId: 6
    chainName: Avalanche
    nativeCurrencySymbol: AVAX
    nodeUrl: https://api.avax-test.network/ext/bc/C/rpc
    tokenBridgeAddress: "0x61E44E506Ca5659E6c0bba9b678586fA2d729756"
    wrappedAsset: "0x1D308089a2D1Ced3f1Ce36B1FcaF815b07217be3"
privateKeys:
  - chainId: 1
    privateKeys:
      # your private key here
      - [
          14,
          173,
          153,
          4,
          176,
          224,
          201,
          111,
          32,
          237,
          183,
          185,
          159,
          247,
          22,
          161,
          89,
          84,
          215,
          209,
          212,
          137,
          10,
          92,
          157,
          49,
          29,
          192,
          101,
          164,
          152,
          70,
          87,
          65,
          8,
          174,
          214,
          157,
          175,
          126,
          98,
          90,
          54,
          24,
          100,
          177,
          247,
          77,
          19,
          112,
          47,
          44,
          165,
          109,
          233,
          102,
          14,
          86,
          109,
          29,
          134,
          145,
          132,
          141,
        ]
  - chainId: 6
    privateKeys:
      - 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
