apiVersion: v1
kind: Service
metadata:
  labels:
    app: near
  name: near
spec:
  ports:
    - name: node
      port: 3030
      targetPort: node
    - name: webserver
      port: 3031
      targetPort: webserver
  selector:
    app: near
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: near
  name: near
spec:
  replicas: 1
  selector:
    matchLabels:
      app: near
  serviceName: near
  template:
    metadata:
      labels:
        app: near
    spec:
      containers:
        - name: near-node
          image: near-node
          env:
            # this still results in DEBUG logs from "stats", but `warn,stats=warn` didn't work
            - name: RUST_LOG
              value: warn
          command:
            - /bin/sh
            - -c
            # because the above still left logs, redirecting stderr
            - "/tmp/start_node.sh 2> /dev/null"
          ports:
            - containerPort: 3030
              name: node
              protocol: TCP
            - containerPort: 3031
              name: webserver
              protocol: TCP
          readinessProbe:
          startupProbe:
            tcpSocket:
              port: 3030
            failureThreshold: 300
            initialDelaySeconds: 20
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 3030
            failureThreshold: 2
            periodSeconds: 1
          resources:
            limits:
              memory: "1000Mi"
---
kind: Job
apiVersion: batch/v1
metadata:
  name: near-deploy
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: near-deploy
          image: near-deploy
          stdin: true
          command:
            - /bin/sh
            - /app/devnet_deploy.sh
          resources:
            limits:
              memory: "500Mi"
