kind: Job
apiVersion: batch/v1
metadata:
  name: sdk-ci-tests
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sdk-ci-tests
          image: sdk-test-image
          command:
            - /bin/sh
            - /app/testing/sdk.sh
          resources:
            limits:
              memory: "2500Mi"
---
kind: Job
apiVersion: batch/v1
metadata:
  name: spydk-ci-tests
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: spydk-ci-tests
          image: spydk-test-image
          command:
            - /bin/sh
            - /app/testing/spydk.sh
          resources:
            limits:
              memory: "1000Mi"